language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install git+https://github.com/matplotlib/basemap.git
before_script:
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render
script:
  - pytest
