build: false

environment:
  matrix: 
    - PYTHON: "C:\\Python36-x64"

init: 
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install: 
  - python
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install ftp://ftpint.usgs.gov/pub/wr/az/flagstaff/jkennedybasemap-1.2.0-cp35-cp35m-win_amd64.whl
  - pip install pytest
  - pip install pytest-qt
  - pwd

test_script: 
  - pytest
  
